# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(227, 227, 227, 255), stop:1 rgba(0, 50, 100, 115));")
        MainWindow.setIconSize(QtCore.QSize(100, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 541))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 311, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgFrame1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.imgFrame1.setMaximumSize(QtCore.QSize(309, 219))
        self.imgFrame1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.imgFrame1.setAlignment(QtCore.Qt.AlignCenter)
        self.imgFrame1.setObjectName("imgFrame1")
        self.verticalLayout.addWidget(self.imgFrame1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_usarResultado1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_usarResultado1.setFont(font)
        self.pushButton_usarResultado1.setAutoFillBackground(False)
        self.pushButton_usarResultado1.setStyleSheet("background-color: rgb(0,50, 100);")
        self.pushButton_usarResultado1.setObjectName("pushButton_usarResultado1")
        self.horizontalLayout_2.addWidget(self.pushButton_usarResultado1)
        self.pushButton_abrirPara1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_abrirPara1.setFont(font)
        self.pushButton_abrirPara1.setStyleSheet("background-color: rgb(0,50, 100);\n"
"")
        self.pushButton_abrirPara1.setObjectName("pushButton_abrirPara1")
        self.horizontalLayout_2.addWidget(self.pushButton_abrirPara1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.imgFrame2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.imgFrame2.setMaximumSize(QtCore.QSize(309, 219))
        self.imgFrame2.setStyleSheet("background-color: rgb(218, 218, 218,0);")
        self.imgFrame2.setAlignment(QtCore.Qt.AlignCenter)
        self.imgFrame2.setObjectName("imgFrame2")
        self.verticalLayout.addWidget(self.imgFrame2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_usarResultado2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_usarResultado2.setFont(font)
        self.pushButton_usarResultado2.setAutoFillBackground(False)
        self.pushButton_usarResultado2.setStyleSheet("background-color: rgb(0,50, 100);")
        self.pushButton_usarResultado2.setObjectName("pushButton_usarResultado2")
        self.horizontalLayout_5.addWidget(self.pushButton_usarResultado2)
        self.pushButton_abrirPara2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_abrirPara2.setFont(font)
        self.pushButton_abrirPara2.setStyleSheet("background-color: rgb(0,50, 100);\n"
"")
        self.pushButton_abrirPara2.setObjectName("pushButton_abrirPara2")
        self.horizontalLayout_5.addWidget(self.pushButton_abrirPara2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 8)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 8)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 421, 341))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.imgFrame3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.imgFrame3.setAlignment(QtCore.Qt.AlignCenter)
        self.imgFrame3.setObjectName("imgFrame3")
        self.verticalLayout_3.addWidget(self.imgFrame3)
        self.panel_group = QtWidgets.QGroupBox(self.groupBox_2)
        self.panel_group.setGeometry(QtCore.QRect(10, 370, 421, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel_group.sizePolicy().hasHeightForWidth())
        self.panel_group.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.panel_group.setFont(font)
        self.panel_group.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.panel_group.setObjectName("panel_group")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.panel_group)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 421, 151))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.panel_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.panel_layout.setContentsMargins(0, 0, 0, 0)
        self.panel_layout.setObjectName("panel_layout")
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuConverter = QtWidgets.QMenu(self.menubar)
        self.menuConverter.setObjectName("menuConverter")
        self.menuTransformar = QtWidgets.QMenu(self.menubar)
        self.menuTransformar.setObjectName("menuTransformar")
        self.menuOp_Aritim_ticas = QtWidgets.QMenu(self.menubar)
        self.menuOp_Aritim_ticas.setObjectName("menuOp_Aritim_ticas")
        self.menuOp_L_gicas = QtWidgets.QMenu(self.menubar)
        self.menuOp_L_gicas.setObjectName("menuOp_L_gicas")
        self.menuElemento_a_elemento = QtWidgets.QMenu(self.menuOp_L_gicas)
        self.menuElemento_a_elemento.setObjectName("menuElemento_a_elemento")
        self.menuBitwise = QtWidgets.QMenu(self.menuOp_L_gicas)
        self.menuBitwise.setObjectName("menuBitwise")
        self.menuBordas = QtWidgets.QMenu(self.menubar)
        self.menuBordas.setObjectName("menuBordas")
        self.menuHistogramas = QtWidgets.QMenu(self.menubar)
        self.menuHistogramas.setObjectName("menuHistogramas")
        self.menuFiltros = QtWidgets.QMenu(self.menubar)
        self.menuFiltros.setObjectName("menuFiltros")
        self.menuMorfologia = QtWidgets.QMenu(self.menubar)
        self.menuMorfologia.setObjectName("menuMorfologia")
        self.menuSegmenta_o = QtWidgets.QMenu(self.menubar)
        self.menuSegmenta_o.setObjectName("menuSegmenta_o")
        self.menuMais = QtWidgets.QMenu(self.menubar)
        self.menuMais.setObjectName("menuMais")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir_para_principal = QtWidgets.QAction(MainWindow)
        self.actionAbrir_para_principal.setObjectName("actionAbrir_para_principal")
        self.actionAbrir_para_auxiliar = QtWidgets.QAction(MainWindow)
        self.actionAbrir_para_auxiliar.setObjectName("actionAbrir_para_auxiliar")
        self.actionSalvar_resultado = QtWidgets.QAction(MainWindow)
        self.actionSalvar_resultado.setObjectName("actionSalvar_resultado")
        self.actionConverter_para_Tons_de_Cinza = QtWidgets.QAction(MainWindow)
        self.actionConverter_para_Tons_de_Cinza.setObjectName("actionConverter_para_Tons_de_Cinza")
        self.actionConverter_para_Preto_e_Branco_bin_rio = QtWidgets.QAction(MainWindow)
        self.actionConverter_para_Preto_e_Branco_bin_rio.setObjectName("actionConverter_para_Preto_e_Branco_bin_rio")
        self.actionAplicar_transforma_es_geom_tricas = QtWidgets.QAction(MainWindow)
        self.actionAplicar_transforma_es_geom_tricas.setObjectName("actionAplicar_transforma_es_geom_tricas")
        self.actionSomar_constante = QtWidgets.QAction(MainWindow)
        self.actionSomar_constante.setObjectName("actionSomar_constante")
        self.actionMultiplicar_por_constante = QtWidgets.QAction(MainWindow)
        self.actionMultiplicar_por_constante.setObjectName("actionMultiplicar_por_constante")
        self.actionSomar_Imagens = QtWidgets.QAction(MainWindow)
        self.actionSomar_Imagens.setObjectName("actionSomar_Imagens")
        self.actionAnd = QtWidgets.QAction(MainWindow)
        self.actionAnd.setObjectName("actionAnd")
        self.actionOr = QtWidgets.QAction(MainWindow)
        self.actionOr.setObjectName("actionOr")
        self.actionXor = QtWidgets.QAction(MainWindow)
        self.actionXor.setObjectName("actionXor")
        self.actionNot = QtWidgets.QAction(MainWindow)
        self.actionNot.setObjectName("actionNot")
        self.actionAnd_2 = QtWidgets.QAction(MainWindow)
        self.actionAnd_2.setObjectName("actionAnd_2")
        self.actionOr_2 = QtWidgets.QAction(MainWindow)
        self.actionOr_2.setObjectName("actionOr_2")
        self.actionXor_2 = QtWidgets.QAction(MainWindow)
        self.actionXor_2.setObjectName("actionXor_2")
        self.actionNot_2 = QtWidgets.QAction(MainWindow)
        self.actionNot_2.setObjectName("actionNot_2")
        self.actionDerivativo = QtWidgets.QAction(MainWindow)
        self.actionDerivativo.setObjectName("actionDerivativo")
        self.actionSobel = QtWidgets.QAction(MainWindow)
        self.actionSobel.setObjectName("actionSobel")
        self.actionKirsch = QtWidgets.QAction(MainWindow)
        self.actionKirsch.setObjectName("actionKirsch")
        self.actionCaracteristicas = QtWidgets.QAction(MainWindow)
        self.actionCaracteristicas.setObjectName("actionCaracteristicas")
        self.actionSURF = QtWidgets.QAction(MainWindow)
        self.actionSURF.setObjectName("actionSURF")
        self.actionHistograma = QtWidgets.QAction(MainWindow)
        self.actionHistograma.setObjectName("actionHistograma")
        self.actionEqualizar = QtWidgets.QAction(MainWindow)
        self.actionEqualizar.setObjectName("actionEqualizar")
        self.actionAutoescala = QtWidgets.QAction(MainWindow)
        self.actionAutoescala.setObjectName("actionAutoescala")
        self.actionLimiarizar_Global = QtWidgets.QAction(MainWindow)
        self.actionLimiarizar_Global.setObjectName("actionLimiarizar_Global")
        self.actionLimiarizar_Otsu = QtWidgets.QAction(MainWindow)
        self.actionLimiarizar_Otsu.setObjectName("actionLimiarizar_Otsu")
        self.actionMedia = QtWidgets.QAction(MainWindow)
        self.actionMedia.setObjectName("actionMedia")
        self.actionMediana = QtWidgets.QAction(MainWindow)
        self.actionMediana.setObjectName("actionMediana")
        self.actionPassa_Alta = QtWidgets.QAction(MainWindow)
        self.actionPassa_Alta.setObjectName("actionPassa_Alta")
        self.actionLaplaciano = QtWidgets.QAction(MainWindow)
        self.actionLaplaciano.setObjectName("actionLaplaciano")
        self.actionDilatar = QtWidgets.QAction(MainWindow)
        self.actionDilatar.setObjectName("actionDilatar")
        self.actionErodir = QtWidgets.QAction(MainWindow)
        self.actionErodir.setObjectName("actionErodir")
        self.actionAbretura = QtWidgets.QAction(MainWindow)
        self.actionAbretura.setObjectName("actionAbretura")
        self.actionFechamento = QtWidgets.QAction(MainWindow)
        self.actionFechamento.setObjectName("actionFechamento")
        self.actionMulti_limiarizar = QtWidgets.QAction(MainWindow)
        self.actionMulti_limiarizar.setObjectName("actionMulti_limiarizar")
        self.actionGaussiano = QtWidgets.QAction(MainWindow)
        self.actionGaussiano.setObjectName("actionGaussiano")
        self.actionRuido = QtWidgets.QAction(MainWindow)
        self.actionRuido.setObjectName("actionRuido")
        self.actionSegmentacao = QtWidgets.QAction(MainWindow)
        self.actionSegmentacao.setObjectName("actionSegmentacao")
        self.menuArquivo.addAction(self.actionAbrir_para_principal)
        self.menuArquivo.addAction(self.actionAbrir_para_auxiliar)
        self.menuArquivo.addAction(self.actionSalvar_resultado)
        self.menuConverter.addAction(self.actionConverter_para_Tons_de_Cinza)
        self.menuConverter.addAction(self.actionConverter_para_Preto_e_Branco_bin_rio)
        self.menuTransformar.addAction(self.actionAplicar_transforma_es_geom_tricas)
        self.menuOp_Aritim_ticas.addAction(self.actionSomar_constante)
        self.menuOp_Aritim_ticas.addAction(self.actionMultiplicar_por_constante)
        self.menuOp_Aritim_ticas.addAction(self.actionSomar_Imagens)
        self.menuElemento_a_elemento.addAction(self.actionAnd)
        self.menuElemento_a_elemento.addAction(self.actionOr)
        self.menuElemento_a_elemento.addAction(self.actionXor)
        self.menuElemento_a_elemento.addAction(self.actionNot)
        self.menuBitwise.addAction(self.actionAnd_2)
        self.menuBitwise.addAction(self.actionOr_2)
        self.menuBitwise.addAction(self.actionXor_2)
        self.menuBitwise.addAction(self.actionNot_2)
        self.menuOp_L_gicas.addAction(self.menuElemento_a_elemento.menuAction())
        self.menuOp_L_gicas.addAction(self.menuBitwise.menuAction())
        self.menuBordas.addAction(self.actionDerivativo)
        self.menuBordas.addAction(self.actionSobel)
        self.menuBordas.addAction(self.actionKirsch)
        self.menuHistogramas.addAction(self.actionHistograma)
        self.menuHistogramas.addAction(self.actionEqualizar)
        self.menuHistogramas.addAction(self.actionAutoescala)
        self.menuHistogramas.addAction(self.actionLimiarizar_Global)
        self.menuHistogramas.addAction(self.actionLimiarizar_Otsu)
        self.menuFiltros.addAction(self.actionMedia)
        self.menuFiltros.addAction(self.actionMediana)
        self.menuFiltros.addAction(self.actionPassa_Alta)
        self.menuFiltros.addAction(self.actionLaplaciano)
        self.menuFiltros.addAction(self.actionGaussiano)
        self.menuMorfologia.addAction(self.actionDilatar)
        self.menuMorfologia.addAction(self.actionErodir)
        self.menuMorfologia.addAction(self.actionAbretura)
        self.menuMorfologia.addAction(self.actionFechamento)
        self.menuSegmenta_o.addAction(self.actionMulti_limiarizar)
        self.menuSegmenta_o.addAction(self.actionSegmentacao)
        self.menuMais.addAction(self.actionCaracteristicas)
        self.menuMais.addAction(self.actionSURF)
        self.menuMais.addAction(self.actionRuido)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuConverter.menuAction())
        self.menubar.addAction(self.menuTransformar.menuAction())
        self.menubar.addAction(self.menuOp_Aritim_ticas.menuAction())
        self.menubar.addAction(self.menuOp_L_gicas.menuAction())
        self.menubar.addAction(self.menuBordas.menuAction())
        self.menubar.addAction(self.menuHistogramas.menuAction())
        self.menubar.addAction(self.menuFiltros.menuAction())
        self.menubar.addAction(self.menuMorfologia.menuAction())
        self.menubar.addAction(self.menuSegmenta_o.menuAction())
        self.menubar.addAction(self.menuMais.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visão Computacional - Renan Sandes 2020.1 - UFS"))
        self.groupBox.setTitle(_translate("MainWindow", "Imagens de entrada"))
        self.imgFrame1.setText(_translate("MainWindow", "Abra para começar."))
        self.pushButton_usarResultado1.setText(_translate("MainWindow", "Usar resultado"))
        self.pushButton_abrirPara1.setText(_translate("MainWindow", "Abrir"))
        self.imgFrame2.setText(_translate("MainWindow", "Abra para começar."))
        self.pushButton_usarResultado2.setText(_translate("MainWindow", "Usar resultado"))
        self.pushButton_abrirPara2.setText(_translate("MainWindow", "Abrir"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Resultado"))
        self.imgFrame3.setText(_translate("MainWindow", "Escolha um operação no menu."))
        self.panel_group.setTitle(_translate("MainWindow", "Controles"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuConverter.setTitle(_translate("MainWindow", "Converter"))
        self.menuTransformar.setTitle(_translate("MainWindow", "Transformar"))
        self.menuOp_Aritim_ticas.setTitle(_translate("MainWindow", "Op.Aritiméticas"))
        self.menuOp_L_gicas.setTitle(_translate("MainWindow", "Op.Lógicas"))
        self.menuElemento_a_elemento.setTitle(_translate("MainWindow", "Elemento a elemento"))
        self.menuBitwise.setTitle(_translate("MainWindow", "Bitwise"))
        self.menuBordas.setTitle(_translate("MainWindow", "Bordas"))
        self.menuHistogramas.setTitle(_translate("MainWindow", "Histogramas"))
        self.menuFiltros.setTitle(_translate("MainWindow", "Filtros"))
        self.menuMorfologia.setTitle(_translate("MainWindow", "Morfologia"))
        self.menuSegmenta_o.setTitle(_translate("MainWindow", "Segmentação"))
        self.menuMais.setTitle(_translate("MainWindow", "Mais"))
        self.actionAbrir_para_principal.setText(_translate("MainWindow", "Abrir para principal"))
        self.actionAbrir_para_auxiliar.setText(_translate("MainWindow", "Abrir para auxiliar"))
        self.actionSalvar_resultado.setText(_translate("MainWindow", "Salvar resultado"))
        self.actionConverter_para_Tons_de_Cinza.setText(_translate("MainWindow", "Converter para Tons de Cinza"))
        self.actionConverter_para_Preto_e_Branco_bin_rio.setText(_translate("MainWindow", "Converter para Preto e Branco (binário)"))
        self.actionAplicar_transforma_es_geom_tricas.setText(_translate("MainWindow", "Aplicar transformações geométricas"))
        self.actionSomar_constante.setText(_translate("MainWindow", "Somar constante"))
        self.actionMultiplicar_por_constante.setText(_translate("MainWindow", "Multiplicar por constante"))
        self.actionSomar_Imagens.setText(_translate("MainWindow", "Somar Imagens"))
        self.actionAnd.setText(_translate("MainWindow", "And"))
        self.actionOr.setText(_translate("MainWindow", "Or"))
        self.actionXor.setText(_translate("MainWindow", "Xor"))
        self.actionNot.setText(_translate("MainWindow", "Not"))
        self.actionAnd_2.setText(_translate("MainWindow", "And"))
        self.actionOr_2.setText(_translate("MainWindow", "Or"))
        self.actionXor_2.setText(_translate("MainWindow", "Xor"))
        self.actionNot_2.setText(_translate("MainWindow", "Not"))
        self.actionDerivativo.setText(_translate("MainWindow", "Derivativo"))
        self.actionSobel.setText(_translate("MainWindow", "Sobel"))
        self.actionKirsch.setText(_translate("MainWindow", "Kirsch"))
        self.actionCaracteristicas.setText(_translate("MainWindow", "Características"))
        self.actionSURF.setText(_translate("MainWindow", "SURF"))
        self.actionHistograma.setText(_translate("MainWindow", "Histograma"))
        self.actionEqualizar.setText(_translate("MainWindow", "Equalizar"))
        self.actionAutoescala.setText(_translate("MainWindow", "Autoescala"))
        self.actionLimiarizar_Global.setText(_translate("MainWindow", "Limiarizar Global"))
        self.actionLimiarizar_Otsu.setText(_translate("MainWindow", "Limiarizar Otsu"))
        self.actionMedia.setText(_translate("MainWindow", "Media"))
        self.actionMediana.setText(_translate("MainWindow", "Mediana"))
        self.actionPassa_Alta.setText(_translate("MainWindow", "Passa Alta"))
        self.actionLaplaciano.setText(_translate("MainWindow", "Laplaciano"))
        self.actionDilatar.setText(_translate("MainWindow", "Dilatação"))
        self.actionErodir.setText(_translate("MainWindow", "Erosão"))
        self.actionAbretura.setText(_translate("MainWindow", "Abretura"))
        self.actionFechamento.setText(_translate("MainWindow", "Fechamento"))
        self.actionMulti_limiarizar.setText(_translate("MainWindow", "Multi limiarização"))
        self.actionGaussiano.setText(_translate("MainWindow", "Gaussiano"))
        self.actionRuido.setText(_translate("MainWindow", "Adicionar Ruido"))
        self.actionSegmentacao.setText(_translate("MainWindow", "Segmentação"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

