# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/ui_transformations_widget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(410, 150)
        Form.setMinimumSize(QtCore.QSize(410, 150))
        Form.setMaximumSize(QtCore.QSize(420, 180))
        Form.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(0, 50, 100);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 10, 311, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_escala = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_escala.setObjectName("lineEdit_escala")
        self.horizontalLayout_4.addWidget(self.lineEdit_escala)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_dx = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_dx.setObjectName("lineEdit_dx")
        self.horizontalLayout_3.addWidget(self.lineEdit_dx)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_dy = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_dy.setObjectName("lineEdit_dy")
        self.horizontalLayout_3.addWidget(self.lineEdit_dy)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.radioButton_deg = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_deg.setChecked(True)
        self.radioButton_deg.setObjectName("radioButton_deg")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton_deg)
        self.horizontalLayout.addWidget(self.radioButton_deg)
        self.radioButton_rad = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_rad.setObjectName("radioButton_rad")
        self.buttonGroup_3.addButton(self.radioButton_rad)
        self.horizontalLayout.addWidget(self.radioButton_rad)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_centro = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_centro.setMaximumSize(QtCore.QSize(60, 16777215))
        self.radioButton_centro.setChecked(True)
        self.radioButton_centro.setObjectName("radioButton_centro")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_centro)
        self.horizontalLayout_2.addWidget(self.radioButton_centro)
        self.radioButton_origem = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_origem.setMaximumSize(QtCore.QSize(60, 16777215))
        self.radioButton_origem.setObjectName("radioButton_origem")
        self.buttonGroup_2.addButton(self.radioButton_origem)
        self.horizontalLayout_2.addWidget(self.radioButton_origem)
        self.radioButton_outro = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_outro.setMaximumSize(QtCore.QSize(60, 16777215))
        self.radioButton_outro.setObjectName("radioButton_outro")
        self.buttonGroup_2.addButton(self.radioButton_outro)
        self.horizontalLayout_2.addWidget(self.radioButton_outro)
        self.lineEdit_cx = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_cx.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cx.sizePolicy().hasHeightForWidth())
        self.lineEdit_cx.setSizePolicy(sizePolicy)
        self.lineEdit_cx.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_cx.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_cx.setObjectName("lineEdit_cx")
        self.horizontalLayout_2.addWidget(self.lineEdit_cx)
        self.lineEdit_cy = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_cy.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_cy.sizePolicy().hasHeightForWidth())
        self.lineEdit_cy.setSizePolicy(sizePolicy)
        self.lineEdit_cy.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_cy.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEdit_cy.setObjectName("lineEdit_cy")
        self.horizontalLayout_2.addWidget(self.lineEdit_cy)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 2)
        self.horizontalLayout_2.setStretch(4, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.radioButton_outro.toggled['bool'].connect(self.lineEdit_cx.setEnabled)
        self.radioButton_outro.toggled['bool'].connect(self.lineEdit_cy.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Resultado"))
        self.label.setText(_translate("Form", "Escala: "))
        self.lineEdit_escala.setStatusTip(_translate("Form", "float"))
        self.lineEdit_escala.setText(_translate("Form", "1"))
        self.label_2.setText(_translate("Form", "Translação:"))
        self.label_4.setText(_translate("Form", "dx:"))
        self.lineEdit_dx.setStatusTip(_translate("Form", "int"))
        self.lineEdit_dx.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "dy:"))
        self.lineEdit_dy.setStatusTip(_translate("Form", "int"))
        self.lineEdit_dy.setText(_translate("Form", "0"))
        self.label_3.setText(_translate("Form", "Rotação:"))
        self.lineEdit_3.setStatusTip(_translate("Form", "float"))
        self.lineEdit_3.setText(_translate("Form", "45"))
        self.radioButton_deg.setText(_translate("Form", "Deg"))
        self.radioButton_rad.setText(_translate("Form", "Rad"))
        self.radioButton_centro.setText(_translate("Form", "Centro"))
        self.radioButton_origem.setText(_translate("Form", "Origem"))
        self.radioButton_outro.setText(_translate("Form", "Outro"))
        self.lineEdit_cx.setStatusTip(_translate("Form", "int"))
        self.lineEdit_cx.setText(_translate("Form", "x"))
        self.lineEdit_cy.setStatusTip(_translate("Form", "int"))
        self.lineEdit_cy.setText(_translate("Form", "y"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

